# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, max_length=6, unique=True)),
                ('ward', models.CharField(max_length=256, null=True)),
                ('borough', models.CharField(max_length=256, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
