# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='postcode',
            field=models.CharField(db_index=True, max_length=7, unique=True),
        ),
    ]
